perf: update native image build configuration

diff --git a/Dockerfile.native b/Dockerfile.native
--- a/Dockerfile.native
+++ b/Dockerfile.native
@@ -46,9 +46,7 @@ VOLUME /jmalcloud/
 
 COPY docker-entrypoint.sh /docker-entrypoint.sh
 
-RUN apt-get update && \
-    apt-get install -y gosu && \
-    chmod +x /docker-entrypoint.sh && \
+RUN chmod +x /docker-entrypoint.sh && \
     rm -rf /var/lib/apt/lists/*
 
 EXPOSE 8088
@@ -56,7 +54,6 @@ EXPOSE 8088
 # FTP Server
 EXPOSE 8089
 
-HEALTHCHECK --interval=30s --timeout=3s --start-period=60s --retries=3 \
-  CMD curl -f http://localhost:8088/public/health > /dev/null || exit 1
+# HEALTHCHECK --interval=30s --timeout=3s --start-period=60s --retries=3 CMD curl -f http://localhost:8088/public/health > /dev/null || exit 1
 
 ENTRYPOINT ["/docker-entrypoint.sh"]
